product/main/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from my_angular import views


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include('my_angular.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/', include('my_rest.urls')),
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    url(r'^personal_cabinet/(?P<pk>.*)/$', views.GetUserId.as_view(), name='personal_kabinet'),
    url(r'^login/$', views.Login.as_view(), name = 'login'),
    url(r'^logout/$', views.LogOut.as_view(), name = 'logout'),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

product/my_angular/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from my_angular import views


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', views.Pages.as_view(), name='pages'),

]

product/my_rest/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from my_rest import views

list_comment = views.CommentViewSet.as_view({
    'get': 'list',
    'post':'create'
    })

comment_detail = views.CommentViewSet.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
    })

list_product = views.ProductViewSet.as_view({
    'get': 'list',
    'post':'create'
    })

product_detail = views.ProductViewSet.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
    })

# list_rate = views.RatesViewSet.as_view({
#     'get': 'list',
#     'post':'create'
#     })
#
# rate_detail = views.RatesViewSet.as_view({
#     'get': 'retrieve',
#     'put': 'update',
#     'patch': 'partial_update',
#     'delete': 'destroy'
#     })


urlpatterns = [
    url(r'^comment/$', list_comment),
    url(r'^comment/(?P<pk>\d+)/$', comment_detail),
    url(r'^product/$', list_product),
    url(r'^product/(?P<pk>\d+)/$', product_detail),
    url(r'^checklogin/$', views.check_login),

]

product/my_angular/models.py
from django.db import models

# Create your models here.

product/my_rest/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User


class Product(models.Model):

    name = models.CharField(max_length=100)
    photo = models.ImageField(upload_to='photo/', default="photo/index.jpg")
    description = models.CharField(max_length=500)

    def __unicode__(self):
        return '{0} {1}'.format( self.name, self.description)

# class Rate(models.Model):
#     user = models.ForeignKey(User, related_name='rates_by_user')
#     product = models.ForeignKey(Product)
#     rate = models.IntegerField(default=0)
#
#     def __unicode__(self):
#         return '{0} {1}'.format( self.user, self.product)

class Comment(models.Model):

    user = models.ForeignKey(User)
    product = models.ForeignKey(Product)
    text = models.CharField(max_length=500)
    date = models.DateTimeField(auto_now_add=True)
    rate = models.IntegerField(default=0)

    def __unicode__(self):
        return '{0} {1}'.format( self.text, self.date)

product/my_angular/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, DetailView, ListView
from my_rest.models import Product, Comment
from django.contrib.auth.models import User
from django.views.generic.edit import FormView, View, UpdateView, DeleteView, BaseUpdateView
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from oauth2_provider.models import Application
from django.contrib.auth import login, logout
from django.http import HttpResponse, HttpResponseRedirect
class Pages(TemplateView):
    template_name = 'my_angular/index.html'


    # def get_context_data(self,*args, **kwargs):
    #     context = super(Pages, self).get_context_data(*args, **kwargs)
    #     context.update(NoteForm=NoteForm())
    #     return context

class GetUserId(UpdateView):
    model = User
    # template_name_suffix = 'personal_cabinet'

    template_name = 'my_angular/personal_cabinet.html'
    success_url = '/personal_cabinet/'
    fields = ['first_name','last_name', 'email']

    def get_context_data(self,*args, **kwargs):
        context = super(GetUserId, self).get_context_data(*args, **kwargs)
        user = self.get_object()
        application = Application.objects.get(user=user)
        context.update(client_id=application.client_id)
        context.update(client_secret=application.client_secret)
        return context


class Login(FormView):
    form_class = AuthenticationForm
    success_url = '/'
    template_name = 'my_angular/login.html'

    def form_valid(self,form):
        user = form.get_user()
        login(self.request, user)
        return super(Login, self).form_valid(form)


class LogOut(View):
    success_url = '/login/'
    template_name = 'my_angular/base.html'

    def get(self,request):
        logout(request)
        return HttpResponseRedirect('/')

product/my_rest/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.response import Response
from models import Product, Comment
from serializers import ProductSerializer, CommentSerializer, CommentGetSerializer, CommentPostSerializer,CommentSerializer
from rest_framework import viewsets,status
from django.shortcuts import HttpResponse
import json

class ProductViewSet(viewsets.ModelViewSet):
    '''
    Returns a list of comments.
    Edit, delete and add new ones.

    For more details about all comment [see here][com].
    [com]: http://127.0.0.1:8000/api/comment/

    '''

    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    # permission_classes = (permissions.IsAuthenticatedOrReadOnly,)



class CommentViewSet(viewsets.ModelViewSet):
    '''
    Returns a list of products.
    Edit, delete and add new ones.

    For more details about all product [see here][ref].
    [ref]: http://127.0.0.1:8000/api/product/

    '''
    queryset = Comment.objects.all()
    serializer_class = CommentPostSerializer
    # permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

    def list(self, request):
        queryset = Comment.objects.all().order_by('-date')
        serializer = CommentGetSerializer(queryset, many=True)

        return Response(serializer.data)

    def retrieve(self, request, pk=None):
        queryset = Comment.objects.filter(product=pk).order_by('-date')
        serializer = CommentGetSerializer(queryset, many=True)
        return Response(serializer.data)

    def create(self, request):
        request.data['user'] = request.user.pk
        serializer = CommentSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

# class RatesViewSet(viewsets.ModelViewSet):
#     """
# 	Returns a list of  rates.
#
# 	"""
#
#     queryset = Rate.objects.all()
#     serializer_class = SerialPostRates
#
#     def list(self, request):
#         queryset = Rate.objects.all()
#         serializer = SerialRates(queryset, many=True)
#
#         return Response(serializer.data)
#
#     def create(self, request):
#         request.data['user'] = request.user.pk
#         serializer = SerialRates(data=request.data)
#         if serializer.is_valid():
#             serializer.save()
#             return Response(serializer.data, status=status.HTTP_201_CREATED)
#         return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
#
#     def retrieve(self, request, pk=None):
#         queryset = Rate.objects.filter(product=pk)
#         serializer = SerialRates(queryset, many=True)
#         return Response(serializer.data)

def check_login(request):
    if request.user.is_authenticated():
        return HttpResponse(json.dumps({'result': {'logged': True}, 'username': request.user.username, 'userpk': request.user.pk}),
                        content_type="application/json")
    else:
        return HttpResponse(json.dumps({'result': {'logged': False}}),
                        content_type="application/json")

product/my_angular/templates/my_angular/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
<meta charset="utf-8">
<!--<meta http-equiv="X-UA-Compatible" content="IE=edge">-->
<!--<meta name="viewport" content="width=device-width, initial-scale=1">-->
<script src="{% static "js/libs/lodash.js" %}"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.min.js"></script>

<script type="text/javascript" src="http://cdn.jsdelivr.net/restangular/latest/restangular.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular-resource.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular-route.js"></script>
<script src="//angular-ui.github.io/ui-router/release/angular-ui-router.js"></script>
<link href="{% static "css/star-rating.min.css" %}" media="all" rel="stylesheet" type="text/css" />
<link href="{% static "css/highslide.css" %}" media="all" rel="stylesheet" type="text/css" />

<link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
<!--<link href="{% static "css/bootstrap-slider.css" %}" rel="stylesheet"/>-->
<title>{% block title %}{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    {% if user.is_authenticated %}
    <p class="navbar-text navbar-left"> {{user.username}}</p>
    {% else%}
    <p class="navbar-text navbar-left"> {{Registration}}</p>
    {% endif %}

    <a href="../login/"> {% if not user.is_authenticated %}
                        <p class="navbar-text navbar-right">. LogIn .</p>
                        {% endif %}
    </a>
    <a href='../../logout'>{% if  user.is_authenticated %}
                        <p class="navbar-text navbar-right">. Exit .</p>
                        {% endif %}</a>
    <a href='../../'> {% if  user.is_authenticated %}
                        <p class="navbar-text navbar-right">. Product .</p>
                        {% endif %}</a>
    <a href='{% url 'personal_kabinet' user.id %}'>{% if  user.is_authenticated %}
                        <p class="navbar-text navbar-right">. Personal .</p>
                        {% endif %}</a>
  </div>
</nav>

    <div id="content"  ng-app="productApp" class="container">
        {% block content %}{% endblock %}
    </div>

{% block footer %}
    <!--<div class="col-xs-offset-6 col-sm-offset-4 col-xs-6 col-sm-4 col-xs-offset-6 col-sm-offset-4">-->
        <!--<p ><center>Thanks for visiting my site.</center></p>-->
    <!--</div>-->
{% endblock %}

    <script src="{% static "js/files/controller.js" %}"></script>

    <script src="{% static "js/libs/star-rating.js" %}"></script>
    <script src="{% static "js/libs/star-rating.min.js" %}"></script>
    <script src="{% static "js/libs/highslide.min.js" %}"></script>
    <script src="{% static "js/libs/highslide-with-gallery.js" %}"></script>

    {% block extra_javascript %}{% endblock extra_javascript %}
    </body>
</html>

product/my_angular/templates/my_angular/index.html
{% extends 'my_angular/base.html' %}
{% block title %}Django !{% endblock %}
{% block content %}



<div class="row">
    <div class = "col-xs-3" >

        <div class="content" ng-controller="ProductController">

                <div class="panel-body">
                    {%verbatim%}
                        <ul class="list-group" ng-repeat="product in productList">
                            <li class="list-group-item" >
                                <a href="#/product_id/{{product.pk}}">
                                {{product.pk}}.
                                {{product.name}}
                                </a>
                            </li>
                        </ul>
                    {%endverbatim%}

            </div>
        </div>
    </div>

    <div ng-view class="view col-xs-9">
    HEllo!!
    </div>
</div>

{% endblock %}

{% load staticfiles %}
{% block extra_javascript %}
<script src="{% static "js/files/product_controller.js" %}"></script>
<script src="{% static "js/files/product_id_controller.js" %}"></script>

{% endblock extra_javascript %}

product/my_angular/templates/my_angular/login.html
{% extends 'my_angular/base.html' %}

{% block title %}Django !{% endblock %}

{% block content %}


<form role="form" action='' method='post' data-toggle="validator">{% csrf_token %}
  <div class="form-group col-md-6 col-md-offset-3 ">
    <label  for="username">Username:</label>
      <input class="form-control" id="id_username" maxlength="254" name="username" type="text" />
   <div class="help-block with-errors"></div>
  </div>
  <div class="form-group col-md-6 col-md-offset-3 ">
    <label  for="pass">Password</label>
     <input class="form-control" id="id_password" name="password" type="password" />
  </div>
  <div class="form-group col-md-6 col-md-offset-3">
     <button type="submit" class="btn btn-primary"  value="Send"> Send</button>
  </div>

	</form>



{% endblock %}

product/my_angular/templates/my_angular/personal_cabinet.html
{% extends 'my_angular/base.html' %}

{% block title %}Django !{% endblock %}

{% block content %}
<form method='post' action='' role="form" enctype="multipart/form-data">{% csrf_token %}


<div class="form-group col-md-6 col-md-offset-3">
    <label for="user_name"> User name:</label>
    <textarea class="form-control" id="id_text" name="first_name" rows=1 width="50px" >{{user.username }}</textarea>
</div>
<div class="form-group col-md-6 col-md-offset-3">
    <label for="client_id"> Client id:</label>
    <textarea class="form-control" id="id_text" name="last_name" rows=1 width="50px" >{{client_id}}</textarea>
</div>
<div class="form-group col-md-6 col-md-offset-3">
    <label for="client_secret"> Client secret:</label>
    <textarea class="form-control" id="id_text" name="email" rows=3 width="50px" >{{client_secret}}</textarea>
</div>


</div>
</form>


{% endblock %}